// location.js

const locations = [
  { id: 1, name: "Paris, France" },
  { id: 2, name: "New York City, USA" },
  { id: 3, name: "Tokyo, Japan" },
  { id: 4, name: "London, England" },
  { id: 5, name: "Rome, Italy" },
  { id: 6, name: "Barcelona, Spain" },
  { id: 7, name: "Sydney, Australia" },
  { id: 8, name: "Dubai, UAE" },
  { id: 9, name: "Singapore" },
  { id: 10, name: "Bangkok, Thailand" },
  { id: 11, name: "Istanbul, Turkey" },
  { id: 12, name: "Hong Kong" },
  { id: 13, name: "Bali, Indonesia" },
  { id: 14, name: "Amsterdam, Netherlands" },
  { id: 15, name: "Prague, Czech Republic" },
  { id: 16, name: "Vienna, Austria" },
  { id: 17, name: "Budapest, Hungary" },
  { id: 18, name: "Berlin, Germany" },
  { id: 19, name: "Venice, Italy" },
  { id: 20, name: "Lisbon, Portugal" },
  { id: 21, name: "San Francisco, USA" },
  { id: 22, name: "Los Angeles, USA" },
  { id: 23, name: "Moscow, Russia" },
  { id: 24, name: "Rio de Janeiro, Brazil" },
  { id: 25, name: "Cape Town, South Africa" },
  { id: 26, name: "Athens, Greece" },
  { id: 27, name: "Cairo, Egypt" },
  { id: 28, name: "Florence, Italy" },
  { id: 29, name: "Milan, Italy" },
  { id: 30, name: "Munich, Germany" },
  { id: 31, name: "Dublin, Ireland" },
  { id: 32, name: "Edinburgh, Scotland" },
  { id: 33, name: "Santorini, Greece" },
  { id: 34, name: "Maldives" },
  { id: 35, name: "Phuket, Thailand" },
  { id: 36, name: "Kuala Lumpur, Malaysia" },
  { id: 37, name: "Shanghai, China" },
  { id: 38, name: "Seoul, South Korea" },
  { id: 39, name: "Toronto, Canada" },
  { id: 40, name: "Vancouver, Canada" },
  { id: 41, name: "Quebec City, Canada" },
  { id: 42, name: "Mexico City, Mexico" },
  { id: 43, name: "Cancun, Mexico" },
  { id: 44, name: "Havana, Cuba" },
  { id: 45, name: "Buenos Aires, Argentina" },
  { id: 46, name: "Machu Picchu, Peru" },
  { id: 47, name: "Cusco, Peru" },
  { id: 48, name: "Lima, Peru" },
  { id: 49, name: "Santiago, Chile" },
  { id: 50, name: "Bogotá, Colombia" },
  { id: 51, name: "Cartagena, Colombia" },
  { id: 52, name: "Panama City, Panama" },
  { id: 53, name: "San José, Costa Rica" },
  { id: 54, name: "Reykjavik, Iceland" },
  { id: 55, name: "Oslo, Norway" },
  { id: 56, name: "Stockholm, Sweden" },
  { id: 57, name: "Copenhagen, Denmark" },
  { id: 58, name: "Helsinki, Finland" },
  { id: 59, name: "Zurich, Switzerland" },
  { id: 60, name: "Geneva, Switzerland" },
  { id: 61, name: "Interlaken, Switzerland" },
  { id: 62, name: "Brussels, Belgium" },
  { id: 63, name: "Luxembourg City, Luxembourg" },
  { id: 64, name: "Krakow, Poland" },
  { id: 65, name: "Warsaw, Poland" },
  { id: 66, name: "Dubrovnik, Croatia" },
  { id: 67, name: "Split, Croatia" },
  { id: 68, name: "Ljubljana, Slovenia" },
  { id: 69, name: "Tallinn, Estonia" },
  { id: 70, name: "Riga, Latvia" },
  { id: 71, name: "Vilnius, Lithuania" },
  { id: 72, name: "Petra, Jordan" },
  { id: 73, name: "Doha, Qatar" },
  { id: 74, name: "Abu Dhabi, UAE" },
  { id: 75, name: "Jerusalem, Israel" },
  { id: 76, name: "Amman, Jordan" },
  { id: 77, name: "Kathmandu, Nepal" },
  { id: 78, name: "Pokhara, Nepal" },
  { id: 79, name: "Kathmandu Valley, Nepal" },
  { id: 80, name: "Agra, India" },
  { id: 81, name: "Jaipur, India" },
  { id: 82, name: "Delhi, India" },
  { id: 83, name: "Mumbai, India" },
  { id: 84, name: "Goa, India" },
  { id: 85, name: "Kerala, India" },
  { id: 86, name: "Varanasi, India" },
  { id: 87, name: "Darjeeling, India" },
  { id: 88, name: "Manali, India" },
  { id: 89, name: "Leh, India" },
  { id: 90, name: "Rishikesh, India" },
  { id: 91, name: "Shimla, India" },
  { id: 92, name: "Mysore, India" },
  { id: 93, name: "Udaipur, India" },
  { id: 94, name: "Chennai, India" },
  { id: 95, name: "Hyderabad, India" },
  { id: 96, name: "Pune, India" },
  { id: 97, name: "Bangalore, India" },
  { id: 98, name: "Kolkata, India" },
  { id: 99, name: "Ahmedabad, India" },
  { id: 100, name: "Lucknow, India" }
];

export default locations;
